SETTINGS:
    SLEEP_BETWEEN_TASKS: [10, 60]
    SLEEP_BETWEEN_WALLETS: [10, 20]
    PAUSE_BETWEEN_SWAPS: [3, 20]
    NOT_SWAP_IF_LESS_THAN: 0.001
    SIMULTANEOUS_ACCOUNTS_IN_WORK: 6

SOLVERS:
    CAPSOLVER_API_KEY: ""

UNICHAIN_BRIDGE:
   BRIDGE_AMOUNT: [0.002, 0.0021]

SELF_SENDER:
    SEND_FROM_PK: ""
    SEND_AMOUNT: [0.1, 0.3]

UNISWAP:
    SWAP_ALL_TO_ETH: False
    SWAP_AMOUNT_PERCENTAGE: [86, 90]

FLOW:
    TASKS: ["swap"]
    RANDOM: False
